import { PaletteItem } from '@workflow-builder/types/common';
import { NodeType } from '@workflow-builder/types/node-types';

import { defaultPropertiesData } from './default-properties-data';
import { schema } from './schema';
import { uischema } from './uischema';

export const aiAgent: PaletteItem = {
  label: 'node.aiAgent.label',
  description: 'node.aiAgent.description',
  type: 'ai-agent',
  icon: 'AiAgent',
  templateType: NodeType.AiNode,
  defaultPropertiesData,
  schema,
  uischema,
  outputSchema: {
    properties: {
      response: { type: 'string', label: 'Response', description: 'The text generated by the AI model' },
      tokensUsed: { type: 'number', label: 'Tokens Used', description: 'Total number of tokens consumed' },
      model: { type: 'string', label: 'Model', description: 'The AI model that was used' },
    },
  },
};
