import { NodeType, type PaletteItem } from '@workflowbuilder/sdk';

import { defaultPropertiesData } from './default-properties-data';
import { type AiAgentSchema, schema } from './schema';
import { uischema } from './uischema';

export const aiAgentPaletteItem: PaletteItem<AiAgentSchema> = {
  label: 'AI Agent',
  description: 'Run an LLM prompt',
  type: 'ai-studio/ai-agent',
  icon: 'AiAgent',
  templateType: NodeType.Node,
  defaultPropertiesData,
  schema,
  uischema,
  // Declares the executor's output so `{{ nodes.<id>.response }}` references
  // (e.g. in decision conditions) resolve to a real mention suggestion instead
  // of rendering as an unresolved "missing mention" pill.
  outputSchema: {
    type: 'default',
    properties: {
      response: { type: 'string', label: 'Response', description: 'The text generated by the AI model' },
    },
  },
};
