import { NodeType } from '@workflowbuilder/sdk';
import type { PaletteItem } from '@workflowbuilder/sdk';

import { defaultPropertiesData } from './default-properties-data';
import { schema } from './schema';
import { uischema } from './uischema';

export const aiAgent: PaletteItem = {
  label: 'node.aiAgent.label',
  description: 'node.aiAgent.description',
  type: 'ai-agent',
  icon: 'AiAgent',
  templateType: NodeType.AiNode,
  defaultPropertiesData,
  schema,
  uischema,
  outputSchema: {
    type: 'default',
    bySourceHandle: {
      success: {
        type: 'object',
        properties: {
          response: {
            type: 'string',
            title: 'Response',
            description: 'The text generated by the AI model',
          },
          tokensUsed: {
            type: 'number',
            title: 'Tokens Used',
            description: 'Total number of tokens consumed',
          },
          model: {
            type: 'string',
            title: 'Model',
            description: 'The AI model that was used',
          },
        },
      },
    },
  },
};
