import type { NodeSchemaOutput } from '@workflowbuilder/sdk';

export const schemaOutput: NodeSchemaOutput = {
  type: 'default',
  bySourceHandle: {
    success: {
      type: 'object',
      properties: {
        response: {
          type: 'string',
          title: 'Response',
          description: 'The text generated by the AI model',
        },
        tokensUsed: {
          type: 'number',
          title: 'Tokens Used',
          description: 'Total number of tokens consumed',
        },
        model: {
          type: 'string',
          title: 'Model',
          description: 'The AI model that was used',
        },
      },
    },
  },
};
